# The configurations you want to execute
# That is, a combination of operating system and python version
# Please add or remove for your needs.
# Check all possible values for python in here: https://docs.travis-ci.com/user/languages/python/
# See how to further configure the matrix of combinations in here: https://docs.travis-ci.com/user/multi-os/

sudo: require

services: 
  - docker
# Command to install dependencies for each configuration.
before_install:
  - docker build -t hanumpandey/docker-react -f Dockerfile.dev .
# # For OSX, you may want to call a script installing virtual env and so on.

# Command to run tests. These are run for each configuration
script:
  - docker run hanumpandey/docker-react npm run test -- --coverage
  
after_success:
  - coveralls


	