language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - docker build -t hanumpandey/docker-react -f Dockerfile.dev .
  - docker run hanumpandey/docker-react npm run test -- --coverage
#  - npm install
#  - npm test
#  - npm run build
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $githubToken
#  local_dir: build
  on:
    branch: master