--- 
before_install: 
  - "docker build -t hanumpandey/docker-react -f Dockerfile.dev ."
script: "docker run hanumpandey/docker-react npm run test -- --coverage"
services: 
  - docker
sudo: required
	