

--- 
cache: 
  directories: 
    - node_modules
deploy: 
  project: ./build/
  provider: surge
  skip_cleanup: true
language: node_js
node_js: 
  - stable
script: 
  - "npm test"
  - "npm run build"
true: 
  branch: master
	